# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbs',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/nbs',
                'lib_path': 'nbs'},
  'syms': {'nbs.core': {'nbs.core.foo': ('core.html#foo', 'nbs/core.py')}}}
